api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /api

video_upload:
    resource: "@VideoUploadBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

oneup_uploader:
    resource: .
    type: uploader