sudo: required

language: php

os:
  - linux

php:
  - 5.6

env:
  - SYMFONY_VERSION=3.2.*  ENVIORMENT=travis

cache:
  directories:
    - $COMPOSER_CACHE_DIR

before_script:
  - phpenv config-add building/user.ini
  - composer selfupdate
  - composer install --dev --prefer-source
  - npm install grunt-cli -g

script: bash php/building/travis.sh

notifications:
  email:
    -  carlotheunissen96@gmail.com

branches:
  only:
  - master
