language: php

os:
  - linux

php:
  - 5.6

env:
  - SYMFONY_VERSION=3.2.*  ENVIORMENT=travis

cache:
  directories:
    - $COMPOSER_CACHE_DIR

before_script:
  - sudo phpenv config-add user.ini
  - sudo composer selfupdate
  - sudo composer install --dev --prefer-source
  - sudo npm install grunt-cli -g

script: sudo bash building/build.sh

notifications:
  email:
    -  carlotheunissen96@gmail.com

branches:
  only:
  - master
