version: 0.0
os: linux
files:
  - source: ./app
    destination: /var/www/app
  - source: ./html
    destination: /var/www/html
  - source: ./src
    destination: /var/www/src
  - source: ./composer.lock
    destination: /var/www/
  - source: ./composer.json
    destination: /var/www/
  - source: ./building/user.ini #the custom user.ini
    destination: /etc/php-7.0.d/
  - source: ./building/httpd.conf #the custom user.ini
    destination: /etc/httpd/conf/

permissions:
  #permissions are set in the ApplicationStart hook

hooks:
   BeforeInstall:
     - location: building/BeforeInstall.sh
       timeout: 600 #10 minutes
       runas: root
   AfterInstall:
      - location: building/AfterInstall.sh
        timeout: 300 #5 minutes
        runas: root
   ApplicationStart:
     - location: building/ApplicationStart.sh
       timeout: 60 #1 minute
       runas: root