imports:
    - { resource: config.yml }
    - { resource: "@VideoUploadBundle/Resources/config/dev_services.yml"}

#bucket is ip restricted ;)
parameters:
    dev_bucket_access: AKIAIIHAAFZ4CZXTLF7A
    dev_bucket_secret: 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
    dev_bucket_name: gifcreatoruat
    dev_bucket_region: eu-central-1

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

video_upload:
    ffprobe_command: C:\Users\carlo\Downloads\ffprobe.exe

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event]
        console:
            type:   console
            channels: [!event, !doctrine]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

#swiftmailer:
#    delivery_addresses: ['me@example.com']
