imports:
    - { resource: config_dev.yml }
    - { resource: "@VideoUploadBundle/Resources/config/uat_services.yml"}

video_upload:
    ffprobe_command: /usr/local/bin/ffprobe

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
