api_gifs:
    path:     /gifs
    defaults: { _controller: ApiBundle:Gif:select }

api_gifs_id:
    path:     /gifs/{id}
    defaults: { _controller: ApiBundle:Gif:getSingleGif }

api_formats:
    path:     /video/formats
    defaults: { _controller: ApiBundle:Video:selectAcceptedFormats }

api_file_size:
    path:     /video/filesize
    defaults: { _controller: ApiBundle:Video:selectMaxFileSize }

api_tags:
    path:     /tags
    defaults: { _controller: ApiBundle:Tag:selectAll }

api_lambda_tag:
    path:     /lambda_tag
    methods: [POST]
    defaults: { _controller: ApiBundle:Tag:SetTags }

api_lambda_gif:
    path:     /testtest
    methods: [POST]
    defaults: { _controller: ApiBundle:Gif:setGif }

api_gifs_popular:
    path:     /tags/popular
    defaults: { _controller: ApiBundle:Tag:getPopularTags }