services:
    api.jwt_token_authenticator:
        class: ApiBundle\Security\LambdaJWTAuthenticator
        arguments: ['@lexik_jwt_authentication.encoder.default']
    api.lambda_user_provider:
            class: ApiBundle\Security\LambdaUserProvider
#    api.example:
#        class: ApiBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
