version: 0.0
os: linux
files:
  - source: Server.js
    destination: /var/nodejs/Server.js
  - source: ./package.json
    destination: /var/nodejs/package.json
  - source: ./config.json
    destination: /var/nodejs/config.json
  - source: ./node_modules
    destination: /var/nodejs/node_modules

permissions:
  #permissions are set in the ApplicationStart hook

hooks:
   BeforeInstall:
     - location: _deploy/BeforeInstall.sh
       timeout: 600 #10 minutes
       runas: root
   AfterInstall:
      - location: _deploy/AfterInstall.sh
        timeout: 300 #5 minutes
        runas: root
   ApplicationStart:
     - location: _deploy/ApplicationStart.sh
       timeout: 60 #1 minute
       runas: root