version: 0.0
os: linux
files:
  - source: ./app
    destination: /var/www/app
  - source: ./html
    destination: /var/www/html
  - source: ./src
    destination: /var/www/src
  - source: ./bin/console
    destination: /var/www/app/console
  - source: ./composer.lock
    destination: /var/www/
  - source: ./composer.json
    destination: /var/www/
  - source: ./var/jwt/public.pem
    destination: /var/www/var/jwt/
  - source: ./_deploy/user.ini #the custom user.ini
    destination: /etc/php-7.0.d/
  - source: ./_deploy/httpd.conf #the custom user.ini
    destination: /etc/httpd/conf/

permissions:
    - object: /var/www
      owner: codedeploy
      group: webservices
      except: [/var/www/var]
      mode: 2740
    - object: /var/www
      owner: codedeploy
      group: webservices
      except: [/var/www/var]
      mode: 2740
      type:
       - directory
    - object: /var/www/var
      owner: apache
      group: webservices
      mode: 2070
      type:
       - directory
    - object: /var/www/var
      owner: apache
      group: webservices
      mode: 2070

hooks:
   BeforeInstall:
     - location: _deploy/BeforeInstall.sh
       timeout: 600 #10 minutes
       runas: root
   AfterInstall:
      - location: _deploy/AfterInstall.sh
        timeout: 300 #5 minutes
        runas: root
      - location: _deploy/Composer.sh
        timeout: 300 #5 minutes
        runas: codedeploy  #same rights as apache
   ApplicationStart:
     - location: _deploy/ApplicationStart.sh
       timeout: 60 #1 minute
       runas: root
